[platformio]
default_envs = aero_hand_wifi
src_dir = .

[env:aero_hand_wifi]
platform = espressif32@6.10.0
board = seeed_xiao_esp32s3
framework = arduino
board_build.partitions = partitions.csv
upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bblanchon/ArduinoJson@7.3.1
    links2004/WebSockets@2.6.1
