name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
          build-root-directory: android

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: apk
          path: android/app/build/outputs/apk/debug/*.apk
